config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth',
                                  passwords: 'passwords/passwords', 
                                  sessions: 'passwords/sessions',
                                  registrations: 'passwords/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

 

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  root "home#index"

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'

  get '/about', to: 'pages#about'
  get '/contact_us', to: 'pages#contact_us'

  get '/filters', to: 'pages#filters'

  #routes profilo utente

  get '/dati_utente', to: 'profilo#dati_utente'
  get '/ristoranti_utente', to: 'profilo#ristoranti_utente'
  get '/recensioni_utente', to: 'profilo#recensioni_utente'
  get '/prenotazioni_utente', to: 'profilo#prenotazioni_utente'

  
  
  resources :profilo
  resources :login
  resources :home
  resources :tipo_cucinas
  resources :likes, only: [:create, :destroy]
  resources :like_recensiones, only: [:create, :destroy]
  resources :ristorantes do
    get 'order_recensione/:order_type', action: :order_recensione, on: :member
    resources :piattos
    resources :foto_ristorantes
    resources :prenotaziones do
      post 'noutente', on: :collection
    end
    resources :recensiones do
      resources :foto_recensiones
    end
  end



end

app/controllers/profilo_controller.rb
class ProfiloController < ApplicationController

    def index
      if !user_signed_in? 
        redirect_to home_index_path
      end
    end

    def dati_utente
      respond_to do |format|
        format.js
      end
    end

    def ristoranti_utente
      if current_user.ristoratore.downcase == 'true' || current_user.ristoratore.downcase == 'si'
        @ristoranti = Ristorante.where(user_id: current_user).page(params[:page]).per(5)
      else
        @ristoranti = Ristorante.joins(:likes).where(likes: {user_id: current_user}).page(params[:page]).per(5)
      end
      respond_to do |format|
        format.js
      end
    end

    def prenotazioni_utente
      if current_user.ristoratore.downcase == 'true' || current_user.ristoratore.downcase == 'si'
        @ristoranti = Ristorante.joins(:prenotaziones).where(user_id: current_user).page(params[:page]).per(5)
      else
        @ristoranti = Ristorante.joins(:prenotaziones).where(prenotaziones: {user_id: current_user}).page(params[:page]).per(5)
      end
      respond_to do |format|
        format.js
      end
    end

    
    def recensioni_utente
      if current_user.ristoratore.downcase == 'true' || current_user.ristoratore.downcase == 'si'
        @ristoranti = Ristorante.joins(:recensiones).where(user_id: current_user).page(params[:page]).per(5)
      else
        @ristoranti = Ristorante.joins(:recensiones).where(recensiones: {user_id: current_user}).page(params[:page]).per(5)
        @recensioni = Recensione.where(user_id: current_user)
      end
      respond_to do |format|
        format.js
      end
    end

  end

app/views/profilo/_dati_utente.html.erb
        <div class="dati-personali">
            <div class="info-field">
                <label>Nome:</label>
                <span><%= current_user.nome %></span>
            </div>
            <div class="info-field">
                <label>Cognome:</label>
                <span><%= current_user.cognome %></span>
            </div>
            <div class="info-field">
                <label>Città:</label>
                <span><%= current_user.citta %></span>
            </div>
            <div class="info-field">
                <label>Provincia:</label>
                <span><%= current_user.provincia %></span>
            </div>
            <div class="info-field">
                <label>CAP:</label>
                <span><%= current_user.cap %></span>
            </div>
            <div class="info-field">
                <label>Email:</label>
                <span><%= current_user.email %></span>
            </div>
            <div class="info-field">
                <label>Ristoratore:</label>
                <span>

                    <% if current_user.ristoratore.downcase=='true' || current_user.ristoratore=='1' %>
                    <%= 'Si' %>
                    <% else %>
                    <%= 'No'%>
                    <% end %>
                </span>
            </div>

        </div>

app/views/profilo/_prenotazioni_utente.html.erb
<% if current_user.ristoratore.downcase == 'true' || current_user.ristoratore.downcase == 'si' %>
<div class="dati-utente" >
  <% @ristoranti.each do |ristorante|%>
            <div class= "result_box">

            <%= link_to ristorante_prenotaziones_path(ristorante) do%>
            <div class="result_image"> 
                <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
            </div>
            <% end %>
            <div class="info-ristorante"> 
                 
                <h4> <%= link_to ristorante.nome, ristorante_prenotaziones_path(ristorante), style:"text-decoration:none;color:black" %></h4>
                <%= link_to "Visualizza tutte le prenotazioni per questo ristorante",ristorante_prenotaziones_path(ristorante), class:"icons", method: :get %>
                <br>
                 
            </div>
        </div>
        <% end %>
        <div id="pag">
         <%= paginate @ristoranti%>
         </div>

</div>
    <% else %>
<div class="dati-utente" >
  <% @ristoranti.each do |ristorante|%>
            <div class= "result_box">
            <%= link_to ristorante_prenotaziones_path(ristorante) do%>
            <div class="result_image"> 
                <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
            </div>
            <% end %>
            <div class="info-ristorante"> 
                 
                <h4> <%= link_to ristorante.nome, ristorante_prenotaziones_path(ristorante), style:"text-decoration:none;color:black" %></h4>
                <%= link_to "Visualizza tutte le prenotazioni per questo ristorante",ristorante_prenotaziones_path(ristorante), class:"icons", method: :get %>
                <br>
                 
            </div>
        </div>
        <% end %>
        <div id="pag">
         <%= paginate @ristoranti%>
         </div>

</div>

<% end %>

app/views/profilo/_recensioni_utente.html.erb
<% if current_user.ristoratore.downcase == 'true' || current_user.ristoratore.downcase == 'si' %>

<div class="dati-utente" >
  <% @ristoranti.each do |ristorante|%>
            <div class= "result_box">
            <%= link_to ristorante do%>
            <div class="result_image"> 
                <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
            </div>
            <% end %>
            <div class="info-ristorante"> 
                 
                <h4> <%= link_to ristorante.nome, ristorante, style:"text-decoration:none;color:black" %></h4>
                <%= link_to "Visualizza Recensioni", ristorante_recensiones_path(ristorante), class:"icons", method: :get %>
                <br>

                 
            </div>
        </div>
        <% end %>
        <div id="pag">
         <%= paginate @ristoranti %>
         </div>

</div>

<% else %>

<div class="dati-utente" >
  <% @ristoranti.each do |ristorante|%>
   <% @recensioni.each do |recensione|%>
            <div class= "result_box">
            <%= link_to ristorante do%>
            <div class="result_image"> 
                <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
            </div>
            <% end %>
            <div class="info-ristorante"> 
                 
                <h4> <%= link_to ristorante.nome, ristorante, style:"text-decoration:none;color:black" %></h4>
                <%= link_to "Visualizza Recensione", ristorante_recensione_path(ristorante,recensione), class:"icons", method: :get %>
                <br>

                 
            </div>
        </div>
        <% end %>
        <% end %>
        <div id="pag">
         <%= paginate @ristoranti %>
         </div>

</div>


<% end %>

app/views/profilo/_ristoranti_utente.html.erb
<% if current_user.ristoratore.downcase=='true' || current_user.ristoratore=='1' || current_user.ristoratore.downcase=='si'%>
    <div class="dati-utente" >
    <% @ristoranti.each do |ristorante|%>
        <div class= "result_box">
        <%= link_to ristorante do%>
            <div class="result_image"> 
                <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
            </div>
        <% end %>
        <div class="info-ristorante">                     
            <h4> <%= link_to ristorante.nome, ristorante, style:"text-decoration:none;color:black" %></h4>

            <%= link_to edit_ristorante_path(ristorante), class:"icons", method: :get do %>
                <i class="fa-solid fa-pen-to-square"></i>
            <% end %>

            <%= link_to ristorante_path(ristorante), class:"icons", :method => 'delete' do %>
                <i class="fa-solid fa-trash"></i>
            <% end %>
            <br>

            <span>Aggiunto il <%= ristorante.created_at.strftime("%d-%m-%Y") %></span>                    
            </div>
        </div>
        <% end %>
    </div>
            <div id="pag">
            <%= paginate @ristoranti %>
            </div>

<% else %>
    <div class="dati-utente" >
    <% @ristoranti.each do |ristorante|%>
                <div class= "result_box">
                <%= link_to ristorante do%>
                <div class="result_image"> 
                    <img src="<%= ristorante.foto_ristorantes.first.url %>" style="width:100px;height:100px;border-radius:5px" >
                </div>
                <% end %>
                <div class="info-ristorante">                     
                    <h4> <%= link_to ristorante.nome, ristorante, style:"text-decoration:none;color:black" %></h4>
                    <%= link_to "Visualizza ristorante",ristorante ,class:"icons" %>                    
                </div>
            </div>
            <% end %>
    </div>
            <div id="pag">
            <%= paginate @ristoranti %>
            </div>
<% end %>

app/views/profilo/dati_utente.js.erb
$('#profile-content').html("<%= escape_javascript(render :partial => 'dati_utente')%>")

app/views/profilo/index.html.erb
<% if $messaggio_notizia.present? %>
  <% flash[:notizia] = $messaggio_notizia %>
  <% $messaggio_notizia = nil %>
<% end %>

<% if $messaggio_errore.present? %>
  <% flash[:alert] = $messaggio_errore %>
  <% $messaggio_errore = nil %>
<% end %>

<div class = "avatar_box">
  <div class = "avatar_img">
    <%= image_tag(current_user.avatar, style: "height:300px; width:300px") %>
  </div>
</div>

<div class = "box_titolo_profilo">
  <div class = "titolo_profilo">
    <%= current_user.nome%> <%= current_user.cognome%>
  </div>
  <%= link_to edit_user_registration_path, class: "modifica_profilo", method: :get do %>
    <i class="fa-solid fa-pen-to-square fa-xl"></i>
  <% end %>
</div>
<div class = "titolo_form">
  <% flash.each do |key, value| %>
    <div class="<%= key %>"><%= value %></div>
  <% end %>
</div>


<div class="profile-body">

    <div class="side-profile">

        <%= link_to "Dati personali", dati_utente_path, class:"profile-section",remote: true %>
        <%= link_to "Prenotazioni", prenotazioni_utente_path, class:"profile-section", remote: true %>
        <%= link_to "Recensioni", recensioni_utente_path, class:"profile-section",remote: true %>

        <% if current_user.ristoratore.downcase=='true' || current_user.ristoratore=='1' || current_user.ristoratore.downcase=='si'%>
            <%= link_to "Ristoranti", ristoranti_utente_path,class:"profile-section" ,remote: true %>
        <% else%>
            <%= link_to "Ristoranti preferiti", ristoranti_utente_path,class:"profile-section" ,remote: true %>
        <%end %>

        
    </div>

    <div id="profile-content">

        <div class="dati-personali">
            <div class="info-field">
                <label>Nome:</label>
                <span><%= current_user.nome %></span>
            </div>
            <div class="info-field">
                <label>Cognome:</label>
                <span><%= current_user.cognome %></span>
            </div>
            <div class="info-field">
                <label>Città:</label>
                <span><%= current_user.citta %></span>
            </div>
            <div class="info-field">
                <label>Provincia:</label>
                <span><%= current_user.provincia %></span>
            </div>
            <div class="info-field">
                <label>CAP:</label>
                <span><%= current_user.cap %></span>
            </div>
            <div class="info-field">
                <label>Email:</label>
                <span><%= current_user.email %></span>
            </div>
            <div class="info-field">
                <label>Ristoratore:</label>
                <span>

                    <% if current_user.ristoratore.downcase=='true' || current_user.ristoratore=='1' || current_user.ristoratore.downcase=='si' %>
                    <%= 'Si' %>
                    <% else %>
                    <%= 'No'%>
                    <% end %>
                </span>
            </div>

        </div>

    </div>

</div>



  

app/views/profilo/prenotazioni_utente.js.erb
$('#profile-content').html("<%= escape_javascript(render :partial => 'prenotazioni_utente')%>")

app/views/profilo/recensioni_utente.js.erb
$('#profile-content').html("<%= escape_javascript(render :partial => 'recensioni_utente')%>")
$('#pag').html("<%= escape_javascript(paginate(@ristoranti, :remote => true).to_s)%>")

app/views/profilo/ristoranti_utente.js.erb
$('#profile-content').html("<%= escape_javascript(render :partial => 'ristoranti_utente')%>")
$('#pag').html("<%= escape_javascript(paginate(@ristoranti, :remote => true).to_s)%>")