config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth',
                                  passwords: 'passwords/passwords', 
                                  sessions: 'passwords/sessions',
                                  registrations: 'passwords/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

 

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  root "home#index"

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'

  get '/about', to: 'pages#about'
  get '/contact_us', to: 'pages#contact_us'

  get '/filters', to: 'pages#filters'

  #routes profilo utente

  get '/dati_utente', to: 'profilo#dati_utente'
  get '/ristoranti_utente', to: 'profilo#ristoranti_utente'
  get '/recensioni_utente', to: 'profilo#recensioni_utente'
  get '/prenotazioni_utente', to: 'profilo#prenotazioni_utente'

  
  
  resources :profilo
  resources :login
  resources :home
  resources :tipo_cucinas
  resources :likes, only: [:create, :destroy]
  resources :like_recensiones, only: [:create, :destroy]
  resources :ristorantes do
    get 'order_recensione/:order_type', action: :order_recensione, on: :member
    resources :piattos
    resources :foto_ristorantes
    resources :prenotaziones do
      post 'noutente', on: :collection
    end
    resources :recensiones do
      resources :foto_recensiones
    end
  end



end

app/models/foto_recensione.rb
class FotoRecensione < ApplicationRecord
  belongs_to :recensione
end

app/models/foto_ristorante.rb
class FotoRistorante < ApplicationRecord
  belongs_to :ristorante, optional: true
  validates :url, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id, uniqueness:{scope: :ristorante_id}
  # Ex:- scope :active, -> {where(:active => true)}}
  belongs_to :ristorante
  belongs_to :user
end

app/models/like_recensione.rb
class LikeRecensione < ApplicationRecord
  validates :user_id, uniqueness:{scope: :recensione_id}
  # Ex:- scope :active, -> {where(:active => true)}}
  belongs_to :recensione
  belongs_to :user
end

app/models/piatto.rb
class Piatto < ApplicationRecord
    belongs_to :ristorante, inverse_of: :piattos
    validates :speciale, inclusion: { in: [true, false] }
end

app/models/prenotazione.rb
class Prenotazione < ApplicationRecord
  belongs_to :user
  belongs_to :ristorante
end

app/models/recensione.rb
class Recensione < ApplicationRecord
  belongs_to :user
  belongs_to :ristorante

  has_many :like_recensiones, dependent: :destroy
end

app/models/ristorante.rb
class Ristorante < ApplicationRecord
  belongs_to :tipo_cucina
  belongs_to :user
  has_many :recensiones, dependent: :destroy
  has_many :prenotaziones, dependent: :destroy

  has_many :foto_ristorantes, dependent: :destroy, inverse_of: :ristorante
  accepts_nested_attributes_for :foto_ristorantes, allow_destroy: true,reject_if: :all_blank

  has_many :piattos, dependent: :destroy, inverse_of: :ristorante
  accepts_nested_attributes_for :piattos, allow_destroy: true,reject_if: :all_blank

  has_many :likes, dependent: :destroy

  searchkick text_middle: %i[nome]

  geocoded_by :address, latitude: :latitudine, longitude: :longitudine


  def address
    [indirizzo, citta].compact.join(', ')
  end

  def self.ransackable_attributes(auth_object = nil)
    ["cap", "citta", "created_at", "descrizione", "email", "id", "indirizzo", "latitudine", "longitudine", "nome", "oraapertura", "orachiusura", "provincia", "regione", "sitoweb1", "sitoweb2", "sitoweb3", "telefono", "tipo_cucina_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["foto_ristorantes", "likes", "piattos", "prenotaziones", "recensiones", "tipo_cucina", "user"]
  end

end

app/models/tipo_cucina.rb
class TipoCucina < ApplicationRecord
    def self.ransackable_attributes(auth_object = nil)
        ["created_at", "descrizione", "id", "nome", "updated_at"]
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github, :google_oauth2]


  validates :email, presence: true, unless: :from_auth?
  validates :password, presence: true, length: { minimum: 8 }, format: { with: /\A(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[!@#$%^&*()_+])/, message: "deve contenere almeno una cifra, una lettera maiuscola, una lettera minuscola e un carattere speciale" }, unless: :from_auth? , if:  :password_required?
  validates :password_confirmation, presence: true, unless: :from_auth?, if: :password_required?
  validates :nome, presence: true, unless: :from_auth?
  validates :cognome, presence: true, unless: :from_auth?
  validates :citta, presence: true, unless: :from_auth?
  validates :cap, presence: true, unless: :from_auth?
  validates :provincia, presence: true, unless: :from_auth?
  
  def from_auth?
    provider.present? && (provider == 'github' || provider == 'google_oauth2')
  end

  def password_required?
    !password.nil? || !password_confirmation.nil?
  end

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0,20]
      
      if provider_data.info.has_key?('first_name')
        names = provider_data.info.name.split(' ')
        user.nome = names.first 
        user.cognome = names.last 
      elsif provider_data.info.has_key?('name')
        user.nome = provider_data.info.name.split('-').first
        user.cognome = provider_data.info.name.split('-').last
      end

      if provider_data.info.has_key?('image')
        user.avatar = provider_data.info.image
      elsif provider_data.info.has_key?('picture')
        user.avatar = provider_data.info.picture
      end
    end
  end

  has_many :recensiones
  has_many :prenotaziones
  has_many :ristorantes
  has_many :likes
  has_many :like_recensiones

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @ristorantes = Ristorante.all
    @type = TipoCucina.all
    @coords = Ristorante.select("latitudine, longitudine, nome, indirizzo, citta, id").as_json
    gon.coordinate = @coords

    @result = Geocoder.search(request.location).first.coordinates
    @vicino = Ristorante.near(@result, 15, units: :km)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :require_login
  
  # POST /likes or /likes.json
  def create
    @like=current_user.likes.new(like_params)
    if !@like.save
      flash[:notice]=@like.errors.full_messages.to_sentence
    end
    #redirect_to @like.ristorante
    render turbo_stream:
      turbo_stream.replace("like_bottone",
        partial:"ristorantes/ristorante_like_form",
        locals: {ristorante_id: @like.ristorante.id})
  end


  # DELETE /likes/1 or /likes/1.json
  def destroy
    @like=current_user.likes.find(params[:id])
    ristorante=@like.ristorante
    @like.destroy
    render turbo_stream:
      turbo_stream.replace("like_bottone",
        partial:"ristorantes/ristorante_like_form",
        locals: {ristorante_id: ristorante.id})
  end

  private
    # Only allow a list of trusted parameters through.
    def like_params
      params.require(:like).permit(:ristorante_id)
    end

  protected

  def require_login
    if !user_signed_in?
      flash[:warning] = 'Devi accedere con il tuo account'
      redirect_to new_user_session_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def about
    end
  
    def contact
    end
  
    def help
    end
  
    def terms_of_service
    end

    def filters

      @q = Ristorante.ransack(params[:q])
      @ristoranti = @q.result(distinct: true).includes(:tipo_cucina).page(params[:page]).per(5)


    end


  end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/piattos_helper.rb
module PiattosHelper
end

app/helpers/prenotaziones_helper.rb
module PrenotazionesHelper
end

app/helpers/recensiones_helper.rb
module RecensionesHelper
end

app/helpers/ristorantes_helper.rb
module RistorantesHelper
end

app/helpers/tipo_cucinas_helper.rb
module TipoCucinasHelper
end

app/views/home/_carousel.html.erb
<div class="my-slider">

    <% @ristorantes.where("").each do |ristorante| %>
    <%= link_to ristorante do%>
      <div class="card-container">
        <div class="overlay"><%= ristorante.nome %> </div>
        <img src="<%= ristorante.foto_ristorantes.first.url %>" alt="..." width="100%" height="100%" class="immagini">

      </div>
      <% end %>
    <% end %>
</div>

<div class="carouselBtns">
  <button class="previous"><i class="fa-solid fa-arrow-left"></i></button>
  <button class="next"><i class="fa-solid fa-arrow-right"></i></button>
</div>

app/views/home/_footer.html.erb
    <footer class="py-4" id="ristorantes_footer">
        <div class="layout">
            <div class="row">

                <div class="col-3 col-sm-3">
                    <h5 style="font-weight: bold;">FoodAdvisor</h5>
                    <ul class="nav flex-column">
                    <li class="nav-item ms-2"><%= link_to 'Chi siamo', about_path, class:"nav-link p-0 l-indice" %></li>
                    <li class="nav-item ms-2"><%= link_to 'Visualizza ristoranti', filters_path, class:"nav-link p-0 l-indice" %></li>
                    </ul>
                </div>


            </div>

            <div style="margin-top:0.8rem; margin-bottom:-1.5rem; font-size: 0.75rem;">
                <p>© 2023 FoodAdvisor Company, Inc. All rights reserved.</p>
            </div>
        </div>
    </footer>

app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-white" id="navbrist">

    <div class="container-fluid">
        <% unless current_page?(new_user_registration_path) || current_page?(new_user_session_path)%>
            <%= link_to "FoodAdvisor", home_index_path, class:"navbar-brand mx-auto" %>

        <% else %>
        <div class="navbar-logo">
            <%= link_to "FoodAdvisor", home_index_path, class:"navbar-brand mx-auto", style:"font-size:30px !important" %>
        </div>
        <% end %>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto">
                        <% if user_signed_in? %>

                                <% if current_user.ristoratore==="true" %>
                                    <%= link_to "Hai un ristorante?", new_ristorante_url , class:"nav-link nav-hv", id:"new-rist"%>
                                <% else %>
                                    <%= link_to "Hai un ristorante?", edit_user_registration_path , class:"nav-link nav-hv", id:"new-rist"%>
                                <% end %>

                            <i class="fa-solid fa-user fa-xl" style="color: orange;"></i>
                            <%= button_to "#{
                                if current_user.nome != '' 
                                    current_user.nome 
                                else 
                                    current_user.email 
                                end 
                            }",
                            profilo_index_path,class:"icona_username",method: :get %>

                            <%= button_to "Log out", destroy_user_session_path,class:"nav-btn", :method => :delete %>
                        <% end %>

                  
                        <% if !user_signed_in? &&  !(current_page?(new_user_registration_path) || current_page?(new_user_session_path)) %>
                            <%= button_to "Login", new_user_session_path, class:"nav-btn",method: :get %>
                        <% end %>
                
            </ul>
        </div>
    </div>

</nav>

app/views/home/_suggestions.html.erb
<div class="suggestion">

    <% @vicino.each do |vicino| %>
    <%= link_to vicino do%>
      <div class="card-container">
        <div class="overlay"><%= vicino.nome %> </div>
        <img src="<%= vicino.foto_ristorantes.first.url %>"  width="100%" height="100%" class="immagini">

      </div>
      <% end %>
    <% end %>
</div>


<div class="carouselBtns2">
  <button class="previous"><i class="fa-solid fa-arrow-left"></i></button>
  <button class="next"><i class="fa-solid fa-arrow-right"></i></button>
</div>

app/views/home/index.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "maps" %>
  <meta name="turbo-visit-control" content="reload">
  <%= javascript_import_module_tag "carousel" %>
<% end %>
<div class="layout">

<h1 class='header_h1'>Alla ricerca di un ristorante?</h1>

    <div class="filtri">
        <% @type.limit(5).each do |tipo| %>
        <%= button_to tipo.nome.capitalize() ,filters_path, class:"filtri-btn", method: :get, params: { :type => tipo.nome } %>
        <% end %>
    </div>


    <div class="search-form">
        <%= render partial: "search/form", locals: {results: []}%>
    </div>

    

        <div class="map-description">
            <p>
            Oppure puoi scegliere un ristorante sulla mappa qui sotto
            </p>
        </div>
        
    <div id="map"></div>


        <div class="carousel-description">
        <div class="carousel-bg"></div>
        <div class="carousel-text">
            <p>
                I ristoranti vicini a te
            </p>
        </div>
        <%= render "suggestions"%>
    </div>


    <div class="carousel-description">
        <div class="carousel-bg2"></div>
        <div class="carousel-text">
            <p>
                Esplora i migliori ristoranti
            </p>
        </div>
        <%= render "carousel"%>
    </div>

</div>