config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth',
                                  passwords: 'passwords/passwords', 
                                  sessions: 'passwords/sessions',
                                  registrations: 'passwords/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

 

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  root "home#index"

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'

  get '/about', to: 'pages#about'
  get '/contact_us', to: 'pages#contact_us'

  get '/filters', to: 'pages#filters'

  #routes profilo utente

  get '/dati_utente', to: 'profilo#dati_utente'
  get '/ristoranti_utente', to: 'profilo#ristoranti_utente'
  get '/recensioni_utente', to: 'profilo#recensioni_utente'
  get '/prenotazioni_utente', to: 'profilo#prenotazioni_utente'

  
  
  resources :profilo
  resources :login
  resources :home
  resources :tipo_cucinas
  resources :likes, only: [:create, :destroy]
  resources :like_recensiones, only: [:create, :destroy]
  resources :ristorantes do
    get 'order_recensione/:order_type', action: :order_recensione, on: :member
    resources :piattos
    resources :foto_ristorantes
    resources :prenotaziones do
      post 'noutente', on: :collection
    end
    resources :recensiones do
      resources :foto_recensiones
    end
  end



end

app/models/ristorante.rb
class Ristorante < ApplicationRecord
  belongs_to :tipo_cucina
  belongs_to :user
  has_many :recensiones, dependent: :destroy
  has_many :prenotaziones, dependent: :destroy

  has_many :foto_ristorantes, dependent: :destroy, inverse_of: :ristorante
  accepts_nested_attributes_for :foto_ristorantes, allow_destroy: true,reject_if: :all_blank

  has_many :piattos, dependent: :destroy, inverse_of: :ristorante
  accepts_nested_attributes_for :piattos, allow_destroy: true,reject_if: :all_blank

  has_many :likes, dependent: :destroy

  searchkick text_middle: %i[nome]

  geocoded_by :address, latitude: :latitudine, longitude: :longitudine


  def address
    [indirizzo, citta].compact.join(', ')
  end

  def self.ransackable_attributes(auth_object = nil)
    ["cap", "citta", "created_at", "descrizione", "email", "id", "indirizzo", "latitudine", "longitudine", "nome", "oraapertura", "orachiusura", "provincia", "regione", "sitoweb1", "sitoweb2", "sitoweb3", "telefono", "tipo_cucina_id"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["foto_ristorantes", "likes", "piattos", "prenotaziones", "recensiones", "tipo_cucina", "user"]
  end

end

app/controllers/ristorantes_controller.rb
class RistorantesController < ApplicationController
  before_action :set_ristorante, only: %i[ show edit update destroy ]
  before_action :has_user, :only => [:new, :create, :edit,:update ,:destroy]

  # GET /ristorantes or /ristorantes.json
  def index
    @ristorantes = Ristorante.all
  end

  # GET /ristorantes/1 or /ristorantes/1.json
  def show
    Ristorante.not_geocoded.each { |ristorante| ristorante.geocode && ristorante.save! }
    @risto_coord = Ristorante.where(id: params[:id]).select("latitudine, longitudine, nome").as_json
    gon.latlongrist = @risto_coord
  end

  # GET /ristorantes/new
  def new
    @ristorante = Ristorante.new
    @ristorante.foto_ristorantes.build
    @ristorante.piattos.build
  end

  # GET /ristorantes/1/edit
  def edit
    @ristorante.foto_ristorantes.build
    @ristorante.piattos.build
  end

  # POST /ristorantes or /ristorantes.json
  def create
    @ristorante = Ristorante.new(ristorante_params)
    @ristorante.user_id= current_user.id
    #prende l'id dell' tramite i parametri della sessione
    #o ti fara creare un account prima del ristorante  
    

    respond_to do |format|
      if @ristorante.save
        format.html { redirect_to ristorante_url(@ristorante), notice: "Ristorante was successfully created." }
        format.json { render :show, status: :created, location: @ristorante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ristorante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ristorantes/1 or /ristorantes/1.json
  def update
    respond_to do |format|
      if @ristorante.update(ristorante_params)
        format.html { redirect_to ristorante_url(@ristorante), notice: "Ristorante was successfully updated." }
        format.json { render :show, status: :ok, location: @ristorante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ristorante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ristorantes/1 or /ristorantes/1.json
  def destroy
    @ristorante = Ristorante.find(params[:id])
    @ristorante.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Ristorante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def order_recensione
    order_type = params[:order_type]
    @ristorante = Ristorante.find(params[:id])
    @recensioni = @ristorante.recensiones.order(order_type.to_sym => :desc)
    render partial: 'recensiones/recensione_elenco_recensioni', locals: { recensioni: @recensioni }
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ristorante
      @ristorante = Ristorante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ristorante_params
      params.require(:ristorante).permit(:nome, :regione, :provincia, :citta, :indirizzo, :cap, :email, :telefono, :sitoweb1, :sitoweb2, :sitoweb3, :descrizione, :oraapertura, :orachiusura,:latitudine,:longitudine,:user_id ,:tipo_cucina_id, foto_ristorantes_attributes:[ :id, :url, :_destroy], piattos_attributes:[ :id,:nome, :descrizione,:prezzo, :speciale, :_destroy] )
    end

    protected
    def has_user
      #unless @current_user
      #  flash[:warning] = 'You must be logged in to create a ristorante.'
      #  redirect_to ristorantes_path
      #end
    end  
end

app/helpers/ristorantes_helper.rb
module RistorantesHelper
end

app/views/ristorantes/_ristorante.html.erb
<div id="<%= dom_id ristorante %>" style="margin:0;padding:0;">



  <% if $messaggio_notizia.present? %>
    <% flash[:notizia] = $messaggio_notizia %>
    <% $messaggio_notizia = nil %>
  <% end %>

  <% if $messaggio_errore.present? %>
    <% flash[:alert] = $messaggio_errore %>
    <% $messaggio_errore = nil %>
  <% end %>

  <div class = "titolo_form">
    <% flash.each do |key, value| %>
      <div class="<%= key %>"><%= value %></div>
    <% end %>
  </div>
    
  <div id="rist">
    <div class="container" id="ristorantes_info">
      <%= render 'ristorante_like_form', ristorante_id: ristorante.id%>        
      <div class="row"  style="margin-left: 10px;margin-bottom: 8px;margin-top: -10px;">
        <% Recensione.where(ristorante_id:params[:id]).group(:ristorante_id).average(:valutazione).each do |id, avg| %>
            <div class="col-auto">
              <i class="fa-solid fa-star fa-lg" <% if avg.to_f>=1%>style="color: orange;"<%else%>style="color: black;"<%end%>></i>
              <i class="fa-solid fa-star fa-lg" <% if avg.to_f>=2%>style="color: orange;"<%else%>style="color: black;"<%end%>></i>
              <i class="fa-solid fa-star fa-lg" <% if avg.to_f>=3%>style="color: orange;"<%else%>style="color: black;"<%end%>></i>
              <i class="fa-solid fa-star fa-lg" <% if avg.to_f>=4%>style="color: orange;"<%else%>style="color: black;"<%end%>></i>
              <i class="fa-solid fa-star fa-lg" <% if avg.to_f>=5%>style="color: orange;"<%else%>style="color: black;"<%end%>></i>
            </div>
        <% end %>
        <% Recensione.where(ristorante_id:params[:id]).group(:ristorante_id).average(:prezzo).each do |id, avg| %>
          <div class="col-auto">
            <i class="fa-solid fa-dollar-sign fa-lg" <% if avg.to_f>=1%>style="color: green;"<%else%>style="color: black;"<%end%>></i>
            <i class="fa-solid fa-dollar-sign fa-lg" <% if avg.to_f>=2%>style="color: green;"<%else%>style="color: black;"<%end%>></i>
            <i class="fa-solid fa-dollar-sign fa-lg" <% if avg.to_f>=3%>style="color: green;"<%else%>style="color: black;"<%end%>></i>
          </div>
        <% end %>    
        <%# <div class="col-auto">n. rec:<%= Recensione.where(ristorante_id:params[:id]).count(:all) %><%#</div> %>
        <div class="col-auto"><i class="fa-solid fa-utensils fa-lg" style="color: gray;"></i> <%= TipoCucina.find(ristorante.tipo_cucina_id).nome %></div>
        <div class="col-auto"><i class="fa-solid fa-clock fa-lg" style="color: black;"></i> <%= ristorante.oraapertura.strftime("%H:%M") %> - <%= ristorante.orachiusura.strftime("%H:%M") %> </div>
        <!-- AddToAny BEGIN -->
        <div class="a2a_kit a2a_kit_size_32 a2a_default_style">
            <a class="a2a_dd" href="https://www.addtoany.com/share"></a>
            <a class="a2a_button_facebook"></a>
            <a class="a2a_button_x"></a>
            <a class="a2a_button_copy_link"></a>
            <a class="a2a_button_google_gmail"></a>
            </div>
        <script async src="https://static.addtoany.com/menu/page.js"></script>
        <!-- AddToAny END -->
      </div>

    </div>

    <div class="" id="ristorantes_menu">

      <ul class="h-list-menu">
        <li class="hid"><a id="button" class="btn btn-light"  href="#section_descrizione">Descrizione</a></li>
        <li class="hid"><a id="button" class="btn btn-light"  href="#section_menu">Menu</a></li>
        <% if user_signed_in? %>
          <% if current_user.ristoratore==="true" && ristorante.user_id===current_user.id%>
            <li><%= link_to 'Recensisci', "#NOTRUCCHI#" ,id:"button" ,class:"btn btn-light" %></li>
          <% else %>
            <li><%= link_to 'Recensisci', new_ristorante_recensione_path(@ristorante) ,id:"button" ,class:"btn btn-light" %></li>
          <% end %>
          <li><%= link_to 'Prenota', new_ristorante_prenotazione_path(@ristorante) ,id:"button" ,class:"btn btn-light" %></li>
        <% else %>
          <li><%= link_to 'Prenota', new_ristorante_prenotazione_path(@ristorante) ,id:"button" ,class:"btn btn-light" %></li>
          <li><%= link_to 'Recensisci', new_user_session_path ,id:"button" ,class:"btn btn-light" %></li>
        <%end%>
        <li class="hid"><a id="button" class="btn btn-light"  href="#section_recensioni">Recensioni</a></li>
        <li class="rev"><a id="button" class="btn btn-light"  href="tel:+39<%= ristorante.telefono %>"><i class="fa fa-phone" style="font-size:20px"></i></a></li>
        <li class="rev"><a id="button" class="btn btn-light"  href="https://www.google.com/maps/dir//<%= ristorante.indirizzo %>,+<%= ristorante.cap %>+<%= ristorante.citta %>+<%= ristorante.provincia %>/@<%= ristorante.latitudine %>,<%= ristorante.longitudine %>/"><i class="fas fa-map-marked-alt" style="font-size:20px"></i></a></li>
      </ul>

    </div>

    <div class="" id="ristorantes_body">
      <table><tr>
        <td id="sx_body">
          <div class="section_carosello">

            <% if FotoRistorante.where(ristorante_id:params[:id]).count(:all)>0 %>

              <div id="carouselExampleIndicators" class="carousel slide carousel-fade bg-light" data-ride="carousel" style="width: 100%;height: min-content;">
                <ol class="carousel-indicators">
                  <% ristorante.foto_ristorantes.each.with_index do |image, i| %>
                  <%# FotoRistorante.where(ristorante_id:params[:id]).select(:url).each.with_index do |image, i| %>
                    <li data-target="#carouselExampleIndicators" data-slide-to=<%= i %> <% if i==0 %>class="active"<%end%> ></li>
                  <%end%>
                </ol>
                <div class="carousel-inner" style="width: 100%;height: min-content;">

                  <% ristorante.foto_ristorantes.each.with_index do |image, i| %>
                  <%# FotoRistorante.where(ristorante_id:params[:id]).each.with_index do |image, i| %>
                    <div class="carousel-item <% if i==0 %>active<%end%>" id="carousel-item-0" style="width: 100%;padding-right:2%;padding-left:2%;">
                      <img src=<%= image.url %> style="width: 100%;max-height: 500px;height: auto;">
                    </div>
                  <%# link_to "See More", image %>
                  <%end%>
                
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                  <span class="carousel-control-prev-icon " aria-hidden="true" ></span>
                  <span class="sr-only" >Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                  <span class="sr-only">Next</span>
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                </a>
              </div>

            <% end %>

          </div>

          <div id="section_descrizione">
            <h3 style="font-weight: bold;">UN PO' DI NOI & EVENTI</h3>
            <textarea rows="5" cols="60" readonly><%= ristorante.descrizione %></textarea>            
          </div>

          <div id="section_menu">
            <% if Piatto.where(ristorante_id:ristorante.id, speciale:1).count>0 %>
              <h3 style="font-weight: bold;">SPECIALITA'</h3>
              <div id="sec_menu" style="margin-bottom:30px;">
                <%# Piatto.where(ristorante_id:params[:id]).each do |piatto| %>
                <% ristorante.piattos.each do |piatto| %>
                  <% if piatto.speciale==true%>
                    <div id="sec_piatto">
                      <div class="row"><div class="col-auto"><h5><%= piatto.nome %></h5></div><div class="col-auto"><p>$<%= piatto.prezzo %></p></div></div>
                      <p ><%= piatto.descrizione%></p>
                    </div>
                  <% end %>
                <% end %>
              </div>
            <% end %>

            <h3 style="font-weight: bold;">MENU</h3>
            <div id="sec_menu">
              <%# Piatto.where(ristorante_id:params[:id]).each do |piatto| %>
              <% ristorante.piattos.each do |piatto| %>
                <% if !piatto.speciale || piatto.speciale==false %>
                    <div id="sec_piatto">
                      <div class="row"><div class="col-auto"><h5><%= piatto.nome %></h5></div><div class="col-auto"><p>$<%= piatto.prezzo %></p></div></div>
                      <p ><%= piatto.descrizione%></p>
                    </div>
                  <% end %>
              <% end %>
            </div>

          </div>

          <div id="section_recensioni">
            <h3 style="font-weight: bold;">RECENSIONI</h3>
            <ul class="filtri-rec">
              <li><%= button_tag '<i class="fa-solid fa-star fa-lg" style="color: orange;"></i> Voto'.html_safe, id: 'order-valutazione', class: 'btn btn-light order-button', data: { order_type: 'valutazione' } %></li>
              <li><%= button_tag '<i class="fa-solid fa-clock fa-lg" style="color: gray;"></i> Data'.html_safe, id: 'order-created_at', class: 'btn btn-light order-button', data: { order_type: 'created_at' } %></li>
              <li><%= button_tag '<i class="fa-solid fa-dollar-sign fa-lg" style="color: green;"></i> Prezzo'.html_safe, id: 'order-prezzo', class: 'btn btn-light order-button', data: { order_type: 'prezzo' } %></li>
            </ul>
            <div id="section_rec">
              <%=render partial:  "recensiones/recensione_elenco_recensioni", locals: { recensioni: ristorante.recensiones }%>
            </div>
          </div>

        </td>
        
        <td id="dx_body">

          <div id="borderdiv" >

            <div id="section_maps">
              <h5 style="padding-left:2%">Mappa</h5>
              <div id="map"></div>  
            </div>

            <div id="section_social">
              <h5 style="font-weight: bold;">Contatta via:</h5>
              <ul class="list-group">
                <li class="list-group-item l-contatti mt-0 mb-0 pb-0"><a class="a-contatti" href="mailto:<%= ristorante.email %>" ><%= ristorante.email %></a></li>
                <li class="list-group-item l-contatti mt-0 mb-0 pb-0"><a class="a-contatti" href="tel:+39<%= ristorante.telefono %>">+39<%= ristorante.telefono %></a></li>
                <% if ristorante.sitoweb1?%><li class="list-group-item l-contatti mt-0 mb-0 pb-0"><a class="a-contatti" href="<%= ristorante.sitoweb1 %>" target="_blank" >Sito principale</a></li><% end %>
                <% if ristorante.sitoweb2?%><li class="list-group-item l-contatti mt-0 mb-0 pb-0"><a class="a-contatti" href="<%= ristorante.sitoweb2 %>" target="_blank">Sito secondario</a></li><% end %>
                <% if ristorante.sitoweb3?%><li class="list-group-item l-contatti mt-0 pb-0"><a class="a-contatti" href="<%= ristorante.sitoweb3 %>" target="_blank">Sito terziario</a></li><% end %>
              </ul> 
              <h5 style="font-weight: bold; margin-top:10px">Indicazioni</h5>
              <a class="l-indicazioni" href="https://www.google.com/maps/dir//<%= ristorante.indirizzo %>,+<%= ristorante.cap %>+<%= ristorante.citta %>+<%= ristorante.provincia %>/@<%= ristorante.latitudine %>,<%= ristorante.longitudine %>/"><%= ristorante.indirizzo %>, <%= ristorante.citta %></a>
            </div>

          </div>

        </td>
      </tr></table>
    </div>

  </div>

</div>

<script>
$(document).ready(function(){
  $("#rist #ristorantes_body table #sx_body #section_recensioni #section_rec .section_recensione #borderdiv table #dx_rec #section_rec_img #row-image #colonna img").on("click", function() { //zoom nell'immagine
      $('#rist #ristorantes_body table #sx_body #section_recensioni #section_rec .section_recensione #borderdiv table #dx_rec #section_rec_img .popup-image').show();
      $('#rist #ristorantes_body table #sx_body #section_recensioni #section_rec .section_recensione #borderdiv table #dx_rec #section_rec_img .popup-image img').attr("src", $(this).attr("src"));
  });

  $("#rist #ristorantes_body table #sx_body #section_recensioni #section_rec .section_recensione #borderdiv table #dx_rec #section_rec_img .popup-image span").on("click", function() { //zoom nell'immagine
      $('#rist #ristorantes_body table #sx_body #section_recensioni #section_rec .section_recensione #borderdiv table #dx_rec #section_rec_img .popup-image').hide();
  });
  
  $('.carousel').carousel({
      interval: 1000
  })

  $('.order-button').on('click', function() {
    var orderType = $(this).data('order-type');
    var ristoranteId =<%= @ristorante.id %>;
    var url = '/ristorantes/' + ristoranteId + '/order_recensione/' + orderType;

    $.ajax({
      url: url,
      type: 'GET',
      success: function(response) {
        $('#section_rec').html(response);
      },
      error: function(error) {
        console.error(error);
      }
    });
  });
});
</script>

app/views/ristorantes/_ristorante_foto_ristorante_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">
    <div class="form-group ">
        <%= f.label :url %>
        <%= f.text_field :url ,class:"form-control" ,placeholder:"Inserisci il link come descritto sopra", required: true %>
    </div>

    <button type="button" data-action="nested-form#remove">Remove foto</button>

    <%= f.hidden_field :_destroy %>
</div>

app/views/ristorantes/_ristorante_like_form.html.erb
<%= turbo_frame_tag "like_bottone" do%>
    <% ris=Ristorante.find_by(id: ristorante_id)%>
    <div class="row">
        <div class="col-auto">
          <h1 style="font-weight: bold;"><%= ris.nome %></h1>
        </div>
        <div class="col-auto">
            <% if user_signed_in?%>
                <% like=current_user.likes.find_by(ristorante_id: ris.id)%>
                <% if like.nil?%>
                    <form action="/likes" method="post" id="like_form">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="like[ristorante_id]" value="<%= ris.id %>">
                    <button type="submit"  class="btn btnlike">
                        <i class='far fa-heart icon-heart'></i> 
                        <strong class="rev" id="pre_like"><%= ris.likes.count%></strong> 
                    </button>
                    </form>
                <%else%>
                    <form action="<%= like_path(like) %>" method="post" id="unlike_form">
                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                    <input type="hidden" name="_method" value="DELETE">
                    <button type="submit"  class="btn btnlike" >
                        <i class='fas fa-heart icon-heart'></i>
                        <strong class="rev" id="pre_unlike"><%= ris.likes.count %></strong> 
                    </button>
                    </form>
                <%end%>
            <%else%>
                <button class="btn btnliker" onclick="redirectToLogin()">
                    <i class='fas fa-heart icon-heart'></i>
                    <strong class="rev"><%= ris.likes.count %></strong>
                </button>
            <%end%>
        </div>
        <div class="col-auto">
            <p id="textcons" class="hid" ><strong>Consigliato da <%=ris.likes.count%> utenti!</strong></p>
        </div>
    </div>
    <script>
        function redirectToLogin() {
            window.location.href = '<%= new_user_session_path %>';
        }
    </script>
<%end%>

app/views/ristorantes/_ristorante_like_recensione_form.html.erb
<%= turbo_frame_tag "likerec_form_#{recensione_id}"  do%>
    <div>
        <% rec=Recensione.find_by(id: recensione_id)%>
        <% if user_signed_in? %>
            <% likerec=current_user.like_recensiones.find_by(recensione_id: rec.id)%>
            <% if likerec.nil?%>
                <form action="/like_recensiones" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="like_recensione[recensione_id]" value="<%= rec.id %>">
                <button type="submit"  class="btn btnliker">
                    <i class='fa-solid fa-thumbs-up fa-lg' style='color: #A1CED8;'></i> <%= rec.like_recensiones.count%>
                </button>
                </form>
            <%else%>
                <form action="<%= like_recensione_path(likerec) %>" method="post">
                <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                <input type="hidden" name="_method" value="DELETE">
                <button type="submit"  class="btn btnliker">
                    <i class='fa-solid fa-thumbs-up fa-lg' style='color: #A1CED8;'></i> <%= rec.like_recensiones.count%>
                </button>
                </form>
            <%end%>
        <%else%>
           <button class="btn btnliker" onclick="redirectToLogin()">
                <i class='fa-solid fa-thumbs-up fa-lg' style='color: #A1CED8;'></i><%= rec.like_recensiones.count%> 
            </button>
        <%end%>
    </div>
    <script>
        function redirectToLogin() {
            window.location.href = '<%= new_user_session_path %>';
        }
    </script>
<%end%>

app/views/ristorantes/_ristorante_piatto_form.html.erb
<div class="nested-form-wrapper" data-new-record="<%= f.object.new_record? %>">  
    <div class="form-group ">
        <h5>Inserisci il piatto</h5>
        <%= f.label :nome %>
        <%= f.text_field :nome ,class:"form-control" ,placeholder:"Inserisci il nome del piatto" , required: true%>
    </div>

    <div class="form-group ">
        <%= f.label :descrizione %>
        <%= f.text_field :descrizione ,class:"form-control" ,placeholder:"Inserisci una breve descrizione del piatto" , required: true%>
    </div>

    <div class="form-group ">
        <%= f.label :prezzo %>
        <%= f.number_field :prezzo ,class:"form-control" ,placeholder:"Inserisci il prezzo del piatto ($)" , required: true%>
    </div>

    <div class="form-group">
        <%= f.label :speciale %>
        <%= f.check_box :speciale %>
    </div>

    <button type="button" data-action="nested-form#remove">Remove piatto</button>

    <%= f.hidden_field :_destroy %>
</div>

app/views/ristorantes/_ristorantes.html.erb
<% ristorantes.each do |ristorante| %>

<div class="box-ristoranti">
    <h2><%= ristorante.nome  %></h2>
    <p><%= ristorante.descrizione %></p>
    <p>
        <%= link_to "Mostra questo ristorante", ristorante, class: "links" %>
    </p>
</div>
<% end %>

app/views/ristorantes/edit.html.erb
    <div class="container" id="newrist">
      <h1>Cambia i dati del tuo Ristorante</h1>

      <%= render "form", ristorante: @ristorante %>

      <br>

      <div id="div-back">
        <%= link_to "Show this ristorante", @ristorante %>
      </div>
    </div>

app/views/ristorantes/index.html.erb
<h1>Ristoranti</h1>

<div id="ristorantes">
  <% @ristorantes.each do |ristorante| %>
    <p>
      <%= ristorante.nome%>
      <%= link_to "Show this ristorante", ristorante %>
    </p>
  <% end %>
</div>

app/views/ristorantes/new.html.erb
    <div class="container" id="newrist">
      <h1>Inserisci i dati del tuo Ristorante</h1>

      <%= render "form",  ristorante: @ristorante%>
      
      <div id="div-back">
        <%= link_to "Back to home", home_index_path %>
      </div>
    </div>

app/views/ristorantes/show.html.erb
<% content_for :head do %>
  <%= javascript_import_module_tag "ristorante_maps" %>
  <meta name="turbo-visit-control" content="reload">

<% end %>
    <%= render @ristorante %>