config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {omniauth_callbacks: 'omniauth',
                                  passwords: 'passwords/passwords', 
                                  sessions: 'passwords/sessions',
                                  registrations: 'passwords/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

 

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'

  post '/logout', to: 'sessions#destroy'
  get '/logout', to: 'sessions#destroy'

  root "home#index"

  post 'search', to: 'search#index', as: 'search'
  post 'search/suggestions', to: 'search#suggestions', as: 'search_suggestions'

  get '/about', to: 'pages#about'
  get '/contact_us', to: 'pages#contact_us'

  get '/filters', to: 'pages#filters'

  #routes profilo utente

  get '/dati_utente', to: 'profilo#dati_utente'
  get '/ristoranti_utente', to: 'profilo#ristoranti_utente'
  get '/recensioni_utente', to: 'profilo#recensioni_utente'
  get '/prenotazioni_utente', to: 'profilo#prenotazioni_utente'

  
  
  resources :profilo
  resources :login
  resources :home
  resources :tipo_cucinas
  resources :likes, only: [:create, :destroy]
  resources :like_recensiones, only: [:create, :destroy]
  resources :ristorantes do
    get 'order_recensione/:order_type', action: :order_recensione, on: :member
    resources :piattos
    resources :foto_ristorantes
    resources :prenotaziones do
      post 'noutente', on: :collection
    end
    resources :recensiones do
      resources :foto_recensiones
    end
  end



end

app/models/foto_ristorante.rb
class FotoRistorante < ApplicationRecord
  belongs_to :ristorante, optional: true
  validates :url, presence: true
end

app/controllers/foto_ristorantes_controller.rb
class FotoRistorantesController < ApplicationController
  before_action :set_foto_ristorante, only: %i[ show edit update destroy ]
  before_action :has_ristorante, :only => [:new, :create, :show]

  # GET /foto_ristorantes or /foto_ristorantes.json
  def index
    @foto_ristorantes = FotoRistorante.all
  end

  # GET /foto_ristorantes/1 or /foto_ristorantes/1.json
  def show
  end

  # GET /foto_ristorantes/new
  def new
    @foto_ristorante = FotoRistorante.new
  end

  # GET /foto_ristorantes/1/edit
  def edit
  end

  # POST /foto_ristorantes or /foto_ristorantes.json
  def create
    @foto_ristorante = FotoRistorante.new(foto_ristorante_params)
    @ristorante.foto_ristorante << @foto_ristorante

    respond_to do |format|
      if @foto_ristorante.save
        format.html { redirect_to ristorante_foto_ristorante_path(@ristorante,@foto_ristorante), notice: "Foto ristorante was successfully created." }
        format.json { render :show, status: :created, location: @foto_ristorante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @foto_ristorante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foto_ristorantes/1 or /foto_ristorantes/1.json
  def update
    respond_to do |format|
      if @foto_ristorante.update(foto_ristorante_params)
        format.html { redirect_to foto_ristorante_url(@foto_ristorante), notice: "Foto ristorante was successfully updated." }
        format.json { render :show, status: :ok, location: @foto_ristorante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @foto_ristorante.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /foto_ristorantes/1 or /foto_ristorantes/1.json
  def destroy
    @foto_ristorante.destroy

    respond_to do |format|
      format.html { redirect_to foto_ristorantes_url, notice: "Foto ristorante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_foto_ristorante
      @foto_ristorante = FotoRistorante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def foto_ristorante_params
      params.require(:foto_ristorante).permit(:url, :ristorante_id)
    end

  protected
  def has_ristorante
    unless (@ristorante = Ristorante.where(:id => params[:ristorante_id]).first)
      flash[:warning] = 'Review must be for an existing movie.'
      redirect_to ristorante_path
    end
  end
end

app/helpers/foto_ristorantes_helper.rb
module FotoRistorantesHelper
end

app/views/foto_ristorantes/_form.html.erb
<%= form_with(model: foto_ristorante) do |form| %>
  <% if foto_ristorante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(foto_ristorante.errors.count, "error") %> prohibited this foto_ristorante from being saved:</h2>

      <ul>
        <% foto_ristorante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :ristorante_id, style: "display: block" %>
    <%= form.text_field :ristorante_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/foto_ristorantes/_foto_ristorante.html.erb
<div id="<%= dom_id foto_ristorante %>">
  <p>
    <strong>Url:</strong>
    <%= foto_ristorante.url %>
  </p>

  <p>
    <strong>Ristorante:</strong>
    <%= foto_ristorante.ristorante_id %>
  </p>

</div>

app/views/foto_ristorantes/edit.html.erb
<h1>Editing foto ristorante</h1>

<%= render "form", foto_ristorante: @foto_ristorante %>

<br>

<div>
  <%= link_to "Show this foto ristorante", @foto_ristorante %> |
  <%= link_to "Back to foto ristorantes", foto_ristorantes_path %>
</div>

app/views/foto_ristorantes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Foto ristorantes</h1>

<div id="foto_ristorantes">
  <% @foto_ristorantes.each do |foto_ristorante| %>
    <%= render foto_ristorante %>
    <p>
      <%= link_to "Show this foto ristorante", foto_ristorante %>
    </p>
  <% end %>
</div>

<%= link_to "New foto ristorante", new_foto_ristorante_path %>

app/views/foto_ristorantes/new.html.erb
<h1>New foto ristorante</h1>

<%= render "form", foto_ristorante: @foto_ristorante %>

<br>

<div>
  <%= link_to "Back to foto ristorantes", foto_ristorantes_path %>
</div>

app/views/foto_ristorantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @foto_ristorante %>

<div>
  <%= link_to "Edit this foto ristorante", edit_foto_ristorante_path(@foto_ristorante) %> |
  <%= link_to "Back to foto ristorantes", foto_ristorantes_path %>

  <%= button_to "Destroy this foto ristorante", @foto_ristorante, method: :delete %>
</div>